language: node_js
node_js:
- 8
branches:
  only:
  - master
install:
- yarn install --ignore-engines
- yarn add parcel-bundler --global
script:
- yarn run build
after_success: 
deploy:
  skip_cleanup: true
  provider: heroku
  buildpack: nodejs
  api_key:
    secure: "$HEROKU_KEY"
  app: "$HEROKU_APP"